import type { PackageExampleConfig } from '@vytches/ddd-contracts';

export const config: PackageExampleConfig = {
  packageName: 'resilience',
  displayName: 'Resilience Patterns',
  version: '1.0.0',
  description:
    'Resilience Patterns provides comprehensive fault tolerance patterns including Circuit Breaker, Retry, Bulkhead, and Timeout strategies with enterprise-grade observability.',
  domain: 'Infrastructure',
  patterns: [
    'circuit-breaker',
    'retry-pattern',
    'bulkhead-pattern',
    'timeout-strategy',
    'composite-resilience',
  ],
  tags: {
    core: ['resilience:core', 'resilience:patterns', 'resilience:fault-tolerance'],
    integrations: [
      'resilience:observability',
      'resilience:metrics',
      'resilience:events',
      'resilience:policies',
    ],
    frameworks: ['resilience:nestjs', 'resilience:express', 'resilience:fastify'],
    patterns: [
      'resilience:circuit-breaker',
      'resilience:retry',
      'resilience:bulkhead',
      'resilience:timeout',
      'resilience:composite',
    ],
  },
  dependencies: ['@vytches/ddd-core', '@vytches/ddd-resilience', '@vytches/ddd-utils'],
  sections: [
    'hero',
    'description',
    'whenToUse',
    'whenNotToUse',
    'examples',
    'useCases',
    'frameworkIntegration',
    'commonPitfalls',
    'troubleshooting',
    'performance',
  ],
  complexityLevels: {
    basic: {
      level: 'basic',
      diSupport: true,
      diRequired: false,
      description: 'Basic resilience patterns with simple fault tolerance',
    },
    intermediate: {
      level: 'intermediate',
      diSupport: true,
      diRequired: true,
      description: 'Advanced resilience patterns with events integration and observability',
    },
    advanced: {
      level: 'advanced',
      diSupport: true,
      diRequired: true,
      description:
        'Enterprise resilience system with policies, messaging, and comprehensive monitoring',
    },
  },
  frameworks: [
    {
      name: 'nestjs',
      displayName: 'NestJS',
      description: 'Integration with NestJS framework',
      complexityLevels: ['basic', 'intermediate', 'advanced'],
      dependencies: ['@nestjs/common', '@nestjs/config'],
    },
    {
      name: 'express',
      displayName: 'Express',
      description: 'Integration with Express framework',
      complexityLevels: ['basic', 'intermediate'],
      dependencies: ['express'],
    },
  ],
  examples: [
    {
      id: 'basic-circuit-breaker',
      name: 'Basic Circuit Breaker',
      file: 'basic/implementation.md',
      tags: ['resilience:core', 'resilience:circuit-breaker', 'fault-tolerance'],
      complexity: 'basic',
      priority: 'high',
      description: 'Basic circuit breaker pattern for external service calls',
      dependencies: ['@vytches/ddd-resilience', '@vytches/ddd-utils'],
    },
    {
      id: 'intermediate-resilience-events',
      name: 'Resilience with Events Integration',
      file: 'intermediate/implementation.md',
      tags: ['resilience:advanced', 'resilience:events', 'resilience:observability'],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Advanced resilience patterns integrated with events system for observability',
      dependencies: [
        '@vytches/ddd-resilience',
        '@vytches/ddd-events',
        '@vytches/ddd-di',
        '@vytches/ddd-utils',
      ],
    },
    {
      id: 'advanced-enterprise-resilience',
      name: 'Enterprise Resilience System',
      file: 'advanced/implementation.md',
      tags: [
        'resilience:enterprise',
        'resilience:policies',
        'resilience:messaging',
        'resilience:comprehensive',
      ],
      complexity: 'advanced',
      priority: 'high',
      description:
        'Enterprise resilience system with policies, messaging, and comprehensive fault tolerance',
      dependencies: [
        '@vytches/ddd-resilience',
        '@vytches/ddd-policies',
        '@vytches/ddd-messaging',
        '@vytches/ddd-events',
        '@vytches/ddd-di',
      ],
    },
  ],
  contentConfig: {
    showImportStatements: true,
    showErrorHandling: true,
    showTesting: true,
    showPerformance: true,
    includeBestPractices: true,
    includeCommonPitfalls: true,
    showVersionHistory: false,
  },
  llmSupport: {
    enabled: true,
    includePrompts: true,
    includeTips: true,
    includePatterns: true,
    optimizeForCodeGeneration: true,
  },
  relatedPackages: {
    events: {
      priority: 'high',
      relationship: 'publishes-to',
      integrationExamples: ['resilience-events', 'failure-notifications'],
    },
    policies: {
      priority: 'medium',
      relationship: 'depends-on',
      integrationExamples: ['resilience-policies', 'failure-policies'],
    },
    messaging: {
      priority: 'medium',
      relationship: 'enables',
      integrationExamples: ['resilient-messaging', 'outbox-resilience'],
    },
    logging: {
      priority: 'medium',
      relationship: 'depends-on',
      integrationExamples: ['resilience-logging', 'failure-audit'],
    },
  },
};
