import type { PackageExampleConfig } from '@vytches/ddd-contracts';

export const config: PackageExampleConfig = {
  packageName: 'event-store',
  displayName: 'Event Store',
  version: '1.0.0',
  description:
    'Event Store provides persistent storage for domain events with advanced features including event replay, stream processing, and serialization strategies for event-driven architectures.',
  domain: 'Infrastructure',
  patterns: ['event-storage', 'event-replay', 'event-serialization', 'stream-processing'],
  tags: {
    core: [
      'event-store:core',
      'event-store:persistence',
      'event-store:streams',
      'event-store:serialization',
    ],
    integrations: [
      'event-store:replay',
      'event-store:adapters',
      'event-store:aggregates',
      'event-store:snapshots',
    ],
    frameworks: ['event-store:nestjs', 'event-store:express', 'event-store:fastify'],
    patterns: [
      'event-store:sourcing',
      'event-store:projection',
      'event-store:versioning',
      'event-store:migration',
    ],
  },
  dependencies: ['@vytches/ddd-core', '@vytches/ddd-event-store', '@vytches/ddd-utils'],
  sections: [
    'hero',
    'description',
    'whenToUse',
    'whenNotToUse',
    'examples',
    'useCases',
    'frameworkIntegration',
    'commonPitfalls',
    'troubleshooting',
    'performance',
  ],
  complexityLevels: {
    basic: {
      level: 'basic',
      diSupport: true,
      diRequired: false,
      description: 'Basic event storage and retrieval with in-memory implementation',
    },
    intermediate: {
      level: 'intermediate',
      diSupport: true,
      diRequired: true,
      description: 'Advanced event replay, serialization strategies, and stream processing',
    },
    advanced: {
      level: 'advanced',
      diSupport: true,
      diRequired: true,
      description:
        'Enterprise event store with distributed storage, optimization, and high availability',
    },
  },
  frameworks: [
    {
      name: 'nestjs',
      displayName: 'NestJS',
      description: 'Integration with NestJS framework',
      complexityLevels: ['basic', 'intermediate', 'advanced'],
      dependencies: ['@nestjs/common', '@nestjs/cqrs'],
    },
    {
      name: 'express',
      displayName: 'Express',
      description: 'Integration with Express framework',
      complexityLevels: ['basic', 'intermediate'],
      dependencies: ['express'],
    },
  ],
  examples: [
    // Basic Examples
    {
      id: 'basic-in-memory-store',
      name: 'In-Memory Event Store',
      file: 'basic/example-1.md',
      tags: ['event-store:core', 'event-store:persistence', 'in-memory-storage', 'basic-usage'],
      complexity: 'basic',
      priority: 'high',
      description:
        'Basic event storage and retrieval using in-memory implementation with stream management',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-events'],
    },
    {
      id: 'basic-event-serialization',
      name: 'Event Serialization Strategies',
      file: 'basic/example-2.md',
      tags: ['event-store:serialization', 'event-store:json', 'data-formats'],
      complexity: 'basic',
      priority: 'high',
      description: 'Different event serialization approaches including JSON and custom formatters',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-utils'],
    },
    {
      id: 'basic-stream-operations',
      name: 'Event Stream Operations',
      file: 'basic/example-3.md',
      tags: ['event-store:streams', 'event-store:reading', 'stream-management'],
      complexity: 'basic',
      priority: 'high',
      description: 'Basic stream operations including reading, filtering, and pagination',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-events'],
    },
    {
      id: 'basic-implementation-overview',
      name: 'Implementation Overview',
      file: 'basic/implementation.md',
      tags: ['event-store:overview', 'event-store:getting-started'],
      complexity: 'basic',
      priority: 'medium',
      description: 'High-level overview of event store implementation patterns and setup',
      dependencies: ['@vytches/ddd-event-store'],
    },
    {
      id: 'basic-use-cases',
      name: 'Event Store Use Cases',
      file: 'basic/use-case.md',
      tags: ['event-store:use-cases', 'event-store:business-scenarios'],
      complexity: 'basic',
      priority: 'medium',
      description: 'Real-world business scenarios and use cases for event storage',
      dependencies: ['@vytches/ddd-event-store'],
    },
    // Intermediate Examples
    {
      id: 'intermediate-event-replay',
      name: 'Event Replay Engine',
      file: 'intermediate/example-1.md',
      tags: ['event-store:replay', 'event-store:recovery', 'historical-processing'],
      complexity: 'intermediate',
      priority: 'high',
      description:
        'Advanced event replay capabilities for system recovery and historical data processing',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-events', '@vytches/ddd-utils'],
    },
    {
      id: 'intermediate-stream-projections',
      name: 'Stream-Based Projections',
      file: 'intermediate/example-2.md',
      tags: ['event-store:projections', 'event-store:read-models', 'stream-processing'],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Building read models and projections directly from event streams',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-projections', '@vytches/ddd-events'],
    },
    {
      id: 'intermediate-versioning-migration',
      name: 'Event Versioning and Migration',
      file: 'intermediate/example-3.md',
      tags: ['event-store:versioning', 'event-store:migration', 'schema-evolution'],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Advanced event versioning strategies and data migration techniques',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-utils', '@vytches/ddd-logging'],
    },
    {
      id: 'intermediate-implementation-guide',
      name: 'Intermediate Implementation Guide',
      file: 'intermediate/implementation.md',
      tags: ['event-store:implementation', 'event-store:patterns'],
      complexity: 'intermediate',
      priority: 'medium',
      description: 'Advanced implementation patterns for event storage systems',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-resilience'],
    },
    {
      id: 'intermediate-use-cases',
      name: 'Enterprise Use Cases',
      file: 'intermediate/use-case.md',
      tags: ['event-store:use-cases', 'event-store:enterprise-scenarios'],
      complexity: 'intermediate',
      priority: 'medium',
      description: 'Enterprise-level use cases for event storage and replay systems',
      dependencies: ['@vytches/ddd-event-store'],
    },
    // Advanced Examples
    {
      id: 'advanced-distributed-store',
      name: 'Distributed Event Store',
      file: 'advanced/example-1.md',
      tags: ['event-store:distributed', 'event-store:scalability', 'high-availability'],
      complexity: 'advanced',
      priority: 'high',
      description:
        'Enterprise distributed event store with sharding, replication, and consistency guarantees',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-resilience', '@vytches/ddd-logging'],
    },
    {
      id: 'advanced-performance-optimization',
      name: 'High-Performance Event Store',
      file: 'advanced/example-2.md',
      tags: ['event-store:performance', 'event-store:optimization', 'high-throughput'],
      complexity: 'advanced',
      priority: 'high',
      description: 'Extreme performance optimization for high-throughput event storage systems',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-utils', '@vytches/ddd-logging'],
    },
    {
      id: 'advanced-enterprise-integration',
      name: 'Enterprise Event Store Platform',
      file: 'advanced/example-3.md',
      tags: ['event-store:enterprise', 'event-store:platform', 'event-store:orchestration'],
      complexity: 'advanced',
      priority: 'high',
      description:
        'Complete enterprise event storage platform with monitoring, analytics, and governance',
      dependencies: [
        '@vytches/ddd-event-store',
        '@vytches/ddd-resilience',
        '@vytches/ddd-logging',
        '@vytches/ddd-messaging',
      ],
    },
    {
      id: 'advanced-implementation-guide',
      name: 'Advanced Implementation Guide',
      file: 'advanced/implementation.md',
      tags: ['event-store:implementation', 'event-store:enterprise-patterns'],
      complexity: 'advanced',
      priority: 'medium',
      description: 'Comprehensive implementation patterns for enterprise-grade event storage',
      dependencies: ['@vytches/ddd-event-store', '@vytches/ddd-resilience'],
    },
    {
      id: 'advanced-use-cases',
      name: 'Enterprise-Scale Use Cases',
      file: 'advanced/use-case.md',
      tags: ['event-store:use-cases', 'event-store:enterprise-scenarios'],
      complexity: 'advanced',
      priority: 'medium',
      description: 'Large-scale enterprise use cases and real-world applications',
      dependencies: ['@vytches/ddd-event-store'],
    },
    // Framework Examples - NestJS
    {
      id: 'nestjs-basic-integration',
      name: 'NestJS Basic Integration',
      file: 'frameworks/nestjs/basic/example-1.md',
      tags: ['event-store:nestjs', 'event-store:manual', 'framework:nestjs'],
      complexity: 'basic',
      priority: 'high',
      description: 'Basic NestJS integration with manual event store setup',
      dependencies: ['@nestjs/common', '@vytches/ddd-event-store'],
    },
    {
      id: 'nestjs-di-integration',
      name: 'NestJS DI Integration',
      file: 'frameworks/nestjs/basic/example-2.md',
      tags: ['event-store:nestjs', 'event-store:di', 'framework:nestjs'],
      complexity: 'basic',
      priority: 'high',
      description: 'NestJS integration using @vytches/ddd-di service locator pattern',
      dependencies: ['@nestjs/common', '@vytches/ddd-event-store', '@vytches/ddd-di'],
    },
    {
      id: 'nestjs-intermediate-integration',
      name: 'NestJS Intermediate Integration',
      file: 'frameworks/nestjs/intermediate/example-1.md',
      tags: [
        'event-store:nestjs',
        'event-store:replay',
        'event-store:projections',
        'framework:nestjs',
      ],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Advanced NestJS integration with event replay and projection capabilities',
      dependencies: [
        '@nestjs/common',
        '@vytches/ddd-event-store',
        '@vytches/ddd-di',
        '@vytches/ddd-projections',
      ],
    },
    {
      id: 'nestjs-advanced-integration',
      name: 'NestJS Advanced Integration',
      file: 'frameworks/nestjs/advanced/example-1.md',
      tags: [
        'event-store:nestjs',
        'event-store:distributed',
        'event-store:enterprise',
        'framework:nestjs',
      ],
      complexity: 'advanced',
      priority: 'high',
      description: 'Enterprise-grade NestJS integration with distributed event store capabilities',
      dependencies: [
        '@nestjs/common',
        '@vytches/ddd-event-store',
        '@vytches/ddd-di',
        '@vytches/ddd-resilience',
      ],
    },
  ],
  contentConfig: {
    showImportStatements: true,
    showErrorHandling: true,
    showTesting: true,
    showPerformance: true,
    includeBestPractices: true,
    includeCommonPitfalls: true,
    showVersionHistory: false,
  },
  llmSupport: {
    enabled: true,
    includePrompts: true,
    includeTips: true,
    includePatterns: true,
    optimizeForCodeGeneration: true,
  },
  relatedPackages: {
    events: {
      priority: 'high',
      relationship: 'consumes-from',
      integrationExamples: ['event-persistence', 'domain-events'],
    },
    aggregates: {
      priority: 'high',
      relationship: 'consumes-from',
      integrationExamples: ['event-sourcing', 'aggregate-persistence'],
    },
    projections: {
      priority: 'medium',
      relationship: 'publishes-to',
      integrationExamples: ['stream-projections', 'read-models'],
    },
    resilience: {
      priority: 'medium',
      relationship: 'enables',
      integrationExamples: ['fault-tolerance', 'performance-optimization'],
    },
  },
};
