/**
 * VD-006a — Report phase.
 *
 * Renders the canonical {@link Matrix} (matrix.ts's Correlate output) into
 * the two committed artifacts:
 *   - `docs/coverage-matrix.json` — canonical, machine-truth. Never
 *     hand-edited; regenerate via `cli.ts` instead.
 *   - `docs/COVERAGE-MATRIX.md`   — human-readable render, generated FROM
 *     the JSON above. Never hand-edited either.
 *
 * AC#7: both outputs must make it unambiguous that this matrix is an
 * ADDITIONAL report alongside the existing L1/L2/L3 test-pyramid coverage
 * gate (`vitest --coverage`) — a `VERIFIED` cell means "a real example file
 * exists and a passing test imports it", NOT "this package has adequate
 * unit test coverage". See the disclaimer embedded in the Markdown header
 * below.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import type { Matrix, MatrixCell, UndeclaredCombination } from './types.js';

/** Repo-relative paths the two rendered artifacts are written to. */
export interface ReportPaths {
  jsonPath: string;
  mdPath: string;
}

/** Pretty-printed, stable JSON serialization of the canonical matrix. */
export function renderMatrixJson(matrix: Matrix): string {
  return `${JSON.stringify(matrix, null, 2)}\n`;
}

/**
 * Two matrices are "the same data" for staleness-checking purposes (D-3(c))
 * when their `cells` and `undeclared` arrays are equal — `generatedAt` is
 * intentionally excluded, since a fresh run always produces a new timestamp
 * even when nothing about repo state changed.
 */
export function matrixDataEquals(a: Matrix, b: Matrix): boolean {
  return (
    JSON.stringify(a.cells) === JSON.stringify(b.cells) &&
    JSON.stringify(a.undeclared) === JSON.stringify(b.undeclared)
  );
}

const ADDITIONAL_REPORT_DISCLAIMER =
  '> **This is an ADDITIONAL report alongside the existing L1/L2/L3 test-pyramid\n' +
  '> coverage gate (`vitest --coverage`) — it is NOT a substitute for it.** A\n' +
  '> `VERIFIED` cell means "a real example file exists and a passing test\n' +
  '> imports it", NOT "this package has adequate unit test coverage". Do not\n' +
  '> conflate the two.';

/**
 * Render the human-readable Markdown table from a {@link Matrix}. Pure
 * function of its input — callers own writing the result to disk (see
 * {@link writeReport}), and tests can assert on the returned string directly
 * without touching the filesystem.
 */
export function renderCoverageMarkdown(matrix: Matrix): string {
  const lines: string[] = [];

  lines.push('# Example Coverage Matrix');
  lines.push('');
  lines.push('> Generated by `tools/example-matrix` from `docs/coverage-matrix.json` — do NOT');
  lines.push('> hand-edit this file. The only hand-maintained input is');
  lines.push('> `tools/example-matrix/expected-combinations.yaml`.');
  lines.push('>');
  lines.push(ADDITIONAL_REPORT_DISCLAIMER);
  lines.push('');
  lines.push(`Generated: ${matrix.generatedAt}`);
  lines.push('');

  lines.push(...renderSummarySection(matrix.cells));
  lines.push(...renderCombinationsSection(matrix.cells));
  lines.push(...renderUndeclaredSection(matrix.undeclared));

  return `${lines.join('\n')}\n`;
}

function renderSummarySection(cells: readonly MatrixCell[]): string[] {
  const counts = { VERIFIED: 0, EXAMPLE_ONLY: 0, DECLARED_MISSING: 0, ABSENT: 0 };
  for (const cell of cells) counts[cell.status]++;

  return [
    '## Summary',
    '',
    '| Status | Count |',
    '| --- | --- |',
    `| VERIFIED | ${counts.VERIFIED} |`,
    `| EXAMPLE_ONLY | ${counts.EXAMPLE_ONLY} |`,
    `| DECLARED_MISSING | ${counts.DECLARED_MISSING} |`,
    `| Total | ${cells.length} |`,
    '',
  ];
}

const LEVEL_ORDER = { 'quick-start': 0, intermediate: 1, advanced: 2 } as const;

function renderCombinationsSection(cells: readonly MatrixCell[]): string[] {
  const sorted = [...cells].sort(
    (a, b) => LEVEL_ORDER[a.level] - LEVEL_ORDER[b.level] || a.name.localeCompare(b.name)
  );

  const lines = [
    '## Combinations',
    '',
    '| Name | Level | Packages | Status | File | Tested by |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  for (const cell of sorted) {
    const status = cell.planned
      ? `${statusBadge(cell.status)} _(planned)_`
      : statusBadge(cell.status);
    lines.push(
      `| ${cell.name} | ${cell.level} | ${cell.packages.join(', ')} | ${status} | ${cell.file ?? '_(none)_'} | ${cell.testedBy.length > 0 ? cell.testedBy.join(', ') : '_(none)_'} |`
    );
  }
  lines.push('');
  lines.push(
    "_(planned) — declared future work per `expected-combinations.yaml`'s `planned: true`; `--check` treats these as soft warnings, not hard failures, until authored._"
  );
  lines.push('');

  return lines;
}

function renderUndeclaredSection(undeclared: readonly UndeclaredCombination[]): string[] {
  const lines = [
    '## Undeclared combinations (soft-fail candidates)',
    '',
    '> D-7: a discovered example file combining 2+ `@vytches/*` packages that no',
    '> `expected-combinations.yaml` entry declares. `--check` reports these as a',
    '> soft warning (CI does not hard-fail on them) — add a manifest entry once',
    '> the combination is intentional.',
    '',
  ];

  if (undeclared.length === 0) {
    lines.push('_None — every multi-package combination is declared._');
    lines.push('');
    return lines;
  }

  lines.push('| File | Packages | Status | Tested by |');
  lines.push('| --- | --- | --- | --- |');
  for (const entry of undeclared) {
    lines.push(
      `| ${entry.file} | ${entry.packages.join(', ')} | ${statusBadge(entry.status)} | ${entry.testedBy.length > 0 ? entry.testedBy.join(', ') : '_(none)_'} |`
    );
  }
  lines.push('');

  return lines;
}

function statusBadge(status: MatrixCell['status'] | UndeclaredCombination['status']): string {
  return status;
}

/** Write both rendered artifacts to disk, creating parent directories as needed. */
export function writeReport(matrix: Matrix, paths: ReportPaths): void {
  mkdirSync(dirname(paths.jsonPath), { recursive: true });
  mkdirSync(dirname(paths.mdPath), { recursive: true });
  writeFileSync(paths.jsonPath, renderMatrixJson(matrix));
  writeFileSync(paths.mdPath, renderCoverageMarkdown(matrix));
}
