import type { PackageExampleConfig } from '@vytches/ddd-contracts';

export const diExampleConfig: PackageExampleConfig = {
  packageName: 'di',
  displayName: 'Dependency Injection',
  version: '1.0.0',
  description:
    'Enterprise-grade dependency injection system with auto-discovery, context isolation, and framework integration capabilities.',
  domain: 'Infrastructure',
  patterns: ['dependency-injection', 'service-locator', 'auto-discovery', 'context-isolation'],

  dependencies: ['@vytches/ddd-utils', '@vytches/ddd-contracts'],

  complexityLevels: {
    basic: {
      level: 'basic',
      diSupport: true,
      diRequired: false,
      description: 'Basic dependency injection patterns and service registration',
    },
    intermediate: {
      level: 'intermediate',
      diSupport: true,
      diRequired: true,
      description: 'Advanced DI patterns with auto-discovery and context isolation',
    },
    advanced: {
      level: 'advanced',
      diSupport: true,
      diRequired: true,
      description: 'Enterprise DI patterns with framework integration and production features',
    },
  },

  frameworks: [
    {
      name: 'nestjs',
      displayName: 'NestJS',
      description: 'NestJS integration with bridge pattern to avoid double instances',
      complexityLevels: ['basic', 'intermediate', 'advanced'],
      dependencies: ['@nestjs/core', '@nestjs/common'],
      minimumVersion: '8.0.0',
    },
  ],

  examples: [
    {
      id: 'basic-service-registration',
      name: 'Basic Service Registration',
      file: 'basic/example-1.md',
      tags: ['di:core', 'di:basic'],
      complexity: 'basic',
      priority: 'high',
      description: 'Simple service registration and resolution patterns',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'service-lifetimes',
      name: 'Service Lifetimes',
      file: 'basic/example-2.md',
      tags: ['di:core', 'di:lifetimes'],
      complexity: 'basic',
      priority: 'high',
      description: 'Understanding and configuring service lifetimes',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'global-service-locator',
      name: 'VytchesDDD Global Service Locator',
      file: 'basic/example-3.md',
      tags: ['di:core', 'di:service-locator'],
      complexity: 'basic',
      priority: 'high',
      description: 'Using the global service locator pattern',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'auto-discovery-system',
      name: 'Auto-Discovery System',
      file: 'intermediate/example-1.md',
      tags: ['di:auto-discovery', 'di:decorators'],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Automatic service discovery with decorators',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'context-isolation',
      name: 'Context Isolation',
      file: 'intermediate/example-2.md',
      tags: ['di:context', 'di:isolation'],
      complexity: 'intermediate',
      priority: 'high',
      description: 'Bounded context isolation for DDD scenarios',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'cqrs-handler-registration',
      name: 'CQRS Handler Registration',
      file: 'intermediate/example-3.md',
      tags: ['di:cqrs', 'di:handlers'],
      complexity: 'intermediate',
      priority: 'medium',
      description: 'Automatic registration of CQRS handlers',
      dependencies: ['@vytches/ddd-di', '@vytches/ddd-cqrs'],
      validation: { fileExists: true },
    },
    {
      id: 'framework-integration-patterns',
      name: 'Framework Integration Patterns',
      file: 'advanced/example-1.md',
      tags: ['di:framework', 'di:integration'],
      complexity: 'advanced',
      priority: 'high',
      description: 'Advanced framework integration with bridge pattern',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'custom-container-implementation',
      name: 'Custom Container Implementation',
      file: 'advanced/example-2.md',
      tags: ['di:container', 'di:custom'],
      complexity: 'advanced',
      priority: 'medium',
      description: 'Building custom container implementations',
      dependencies: ['@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'enterprise-production-patterns',
      name: 'Enterprise Production Patterns',
      file: 'advanced/example-3.md',
      tags: ['di:enterprise', 'di:production'],
      complexity: 'advanced',
      priority: 'high',
      description: 'Production-ready DI patterns with monitoring',
      dependencies: ['@vytches/ddd-di', '@vytches/ddd-logging'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-basic-integration',
      name: 'NestJS Basic Integration',
      file: 'frameworks/nestjs/basic/example-1.md',
      tags: ['di:nestjs', 'di:basic'],
      complexity: 'basic',
      framework: 'nestjs',
      priority: 'high',
      description: 'Basic NestJS integration with manual setup',
      dependencies: ['@nestjs/core', '@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-module-configuration',
      name: 'NestJS Module Configuration',
      file: 'frameworks/nestjs/basic/example-2.md',
      tags: ['di:nestjs', 'di:module'],
      complexity: 'basic',
      framework: 'nestjs',
      priority: 'medium',
      description: 'Configuring NestJS modules with VytchesDDD',
      dependencies: ['@nestjs/core', '@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-bridge-pattern',
      name: 'NestJS Bridge Pattern',
      file: 'frameworks/nestjs/intermediate/example-1.md',
      tags: ['di:nestjs', 'di:bridge'],
      complexity: 'intermediate',
      framework: 'nestjs',
      priority: 'high',
      description: 'Bridge pattern to avoid double instance risk',
      dependencies: ['@nestjs/core', '@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-provider-factory',
      name: 'NestJS Custom Provider Factory',
      file: 'frameworks/nestjs/intermediate/example-2.md',
      tags: ['di:nestjs', 'di:factory'],
      complexity: 'intermediate',
      framework: 'nestjs',
      priority: 'medium',
      description: 'Custom provider factory for complex scenarios',
      dependencies: ['@nestjs/core', '@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-multi-context',
      name: 'NestJS Multi-Context Architecture',
      file: 'frameworks/nestjs/advanced/example-1.md',
      tags: ['di:nestjs', 'di:multi-context'],
      complexity: 'advanced',
      framework: 'nestjs',
      priority: 'high',
      description: 'Multi-context architecture for large applications',
      dependencies: ['@nestjs/core', '@vytches/ddd-di'],
      validation: { fileExists: true },
    },
    {
      id: 'nestjs-production-monitoring',
      name: 'NestJS Production Monitoring',
      file: 'frameworks/nestjs/advanced/example-2.md',
      tags: ['di:nestjs', 'di:monitoring'],
      complexity: 'advanced',
      framework: 'nestjs',
      priority: 'medium',
      description: 'Production monitoring and diagnostics',
      dependencies: ['@nestjs/core', '@vytches/ddd-di', '@vytches/ddd-logging'],
      validation: { fileExists: true },
    },
  ],

  tags: {
    core: ['di:core', 'di:basic', 'di:service-locator'],
    integrations: ['di:auto-discovery', 'di:decorators', 'di:context', 'di:cqrs'],
    frameworks: ['di:nestjs', 'di:bridge', 'di:factory'],
    patterns: ['di:framework', 'di:integration', 'di:container', 'di:enterprise', 'di:production'],
  },

  contentConfig: {
    showImportStatements: true,
    showErrorHandling: true,
    showTesting: true,
    showPerformance: true,
    includeBestPractices: true,
    includeCommonPitfalls: true,
    showVersionHistory: false,
  },

  llmSupport: {
    enabled: true,
    includePrompts: true,
    includeTips: true,
    includePatterns: true,
    optimizeForCodeGeneration: true,
  },

  sections: [
    'hero',
    'description',
    'whenToUse',
    'whenNotToUse',
    'examples',
    'useCases',
    'frameworkIntegration',
    'commonPitfalls',
    'troubleshooting',
    'performance',
  ],

  relatedPackages: {
    core: {
      priority: 'high',
      relationship: 'enables',
      integrationExamples: ['basic-service-registration', 'global-service-locator'],
    },
    cqrs: {
      priority: 'high',
      relationship: 'enables',
      integrationExamples: ['cqrs-handler-registration'],
    },
    logging: {
      priority: 'medium',
      relationship: 'enables',
      integrationExamples: ['enterprise-production-patterns'],
    },
  },
};
