/**
 * @fileoverview Customer Aggregate Root
 * Domain: Default
 * Generated by VytchesDDD CLI
 */

import { AggregateRoot, EntityId } from '@vytches-ddd/core';

/**
 * Customer aggregate
 */
export class Customer extends AggregateRoot {
  private constructor(
    id: EntityId,
  ) {
    super({ id });
  }

  /**
   * Factory method to create a new Customer
   */
  static create(
  ): Customer {
    const id = EntityId.createWithRandomUUID();
    
    // Validate business rules

    const aggregate = new Customer(
      id,
    );


    return aggregate;
  }

  /**
   * Reconstitute aggregate from persistence
   */
  static fromPersistence(
    id: EntityId,
  ): Customer {
    return new Customer(
      id,
    );
  }

  // Getters


  /**
   * Get aggregate snapshot for persistence
   */
  toSnapshot(): CustomerSnapshot {
    return {
      id: this.getId().value,
      version: this.getVersion(),
      createdAt: new Date(), // TODO: Add proper timestamp tracking
      updatedAt: new Date(), // TODO: Add proper timestamp tracking
    };
  }
}

/**
 * Aggregate snapshot for persistence
 */
export interface CustomerSnapshot {
  id: string;
  version: number;
  createdAt: Date;
  updatedAt: Date;
}