import type { IDomainEvent } from '@vytches/ddd-contracts';
import type { ISaga, ISagaDefinition, ISagaExecutionContext } from './saga.interfaces';

export interface ISagaOrchestrator {
  /**
   * Start a new saga instance
   * @param event - Event that triggers saga start
   * @param context - Execution context
   * @returns Started saga instance
   */
  startSaga(event: IDomainEvent, context: ISagaExecutionContext): Promise<ISaga>;

  /**
   * Process incoming event against all active sagas
   * @param event - Domain event to process
   * @param context - Execution context
   * @returns Array of processing results
   */
  processEvent(
    event: IDomainEvent,
    context: ISagaExecutionContext
  ): Promise<ISagaProcessingResult[]>;

  /**
   * Complete a saga successfully
   * @param sagaId - Saga identifier
   * @param context - Execution context
   */
  completeSaga(sagaId: string, context: ISagaExecutionContext): Promise<void>;

  /**
   * Cancel a saga
   * @param sagaId - Saga identifier
   * @param reason - Cancellation reason
   * @param context - Execution context
   */
  cancelSaga(sagaId: string, reason: string, context: ISagaExecutionContext): Promise<void>;

  /**
   * Compensate a failed saga
   * @param sagaId - Saga identifier
   * @param context - Execution context
   */
  compensateSaga(sagaId: string, context: ISagaExecutionContext): Promise<void>;

  /**
   * Handle saga timeout
   * @param sagaId - Saga identifier
   * @param context - Execution context
   */
  handleTimeout(sagaId: string, context: ISagaExecutionContext): Promise<void>;

  /**
   * Register saga definition
   * @param definition - Saga definition to register
   */
  registerSagaDefinition(definition: ISagaDefinition): void;

  /**
   * Get registered saga definitions
   * @returns Array of registered saga definitions
   */
  getSagaDefinitions(): ISagaDefinition[];

  /**
   * Get saga definition by type
   * @param sagaType - Type of saga definition
   * @returns Saga definition or null if not found
   */
  getSagaDefinition(sagaType: string): ISagaDefinition | null;

  /**
   * Process timed out sagas
   * @param context - Execution context
   * @returns Number of sagas processed
   */
  processTimedOutSagas(context: ISagaExecutionContext): Promise<number>;

  /**
   * Get saga orchestrator statistics
   * @returns Current orchestrator statistics
   */
  getStatistics(): ISagaOrchestratorStatistics;
}

export interface ISagaProcessingResult {
  /** Saga that processed the event */
  sagaId: string;

  /** Type of saga that processed the event */
  sagaType: string;

  /** Whether processing was successful */
  success: boolean;

  /** Error information if processing failed */
  error?: {
    message: string;
    code: string;
    step?: string;
    details?: Record<string, unknown>;
  };

  /** Commands generated by saga processing */
  commands: unknown[];

  /** Events generated by saga processing */
  events: IDomainEvent[];

  /** Whether saga completed as result of this processing */
  sagaCompleted: boolean;

  /** Whether saga failed and requires compensation */
  requiresCompensation: boolean;

  /** Processing metrics */
  metrics: {
    processingTimeMs: number;
    stepExecuted: string;
    timestamp: Date;
  };
}

export interface ISagaOrchestratorConfig {
  /** Maximum number of concurrent saga executions */
  maxConcurrentExecutions?: number;

  /** Default timeout for saga operations (milliseconds) */
  defaultOperationTimeout?: number;

  /** Default timeout for saga completion (milliseconds) */
  defaultSagaTimeout?: number;

  /** Enable automatic retry for failed operations */
  enableAutoRetry?: boolean;

  /** Maximum retry attempts for failed operations */
  maxRetryAttempts?: number;

  /** Retry delay strategy */
  retryDelay?: {
    initial: number;
    multiplier: number;
    maximum: number;
  };

  /** Enable saga metrics collection */
  enableMetrics?: boolean;

  /** Enable saga event auditing */
  enableAuditing?: boolean;

  /** Dead letter queue configuration */
  deadLetterQueue?: {
    enabled: boolean;
    maxRetentionDays: number;
    notificationThreshold: number;
  };

  /** Performance monitoring configuration */
  performance?: {
    enableProfiling: boolean;
    slowOperationThresholdMs: number;
    metricsCollectionInterval: number;
  };

  /** Saga cleanup configuration */
  cleanup?: {
    enableAutoCleanup: boolean;
    completedSagaRetentionDays: number;
    failedSagaRetentionDays: number;
    cleanupIntervalHours: number;
  };
}

export interface ISagaOrchestratorStatistics {
  /** Total number of active sagas */
  activeSagas: number;

  /** Sagas by status */
  sagasByStatus: Record<string, number>;

  /** Sagas by type */
  sagasByType: Record<string, number>;

  /** Total events processed */
  totalEventsProcessed: number;

  /** Events processed per minute (average) */
  eventsPerMinute: number;

  /** Average saga completion time */
  averageCompletionTimeMs: number;

  /** Success rate (percentage) */
  successRate: number;

  /** Number of compensated sagas */
  compensatedSagas: number;

  /** Number of timed out sagas */
  timedOutSagas: number;

  /** Current system load metrics */
  systemLoad: {
    cpuUsage: number;
    memoryUsage: number;
    activeConnections: number;
  };

  /** Performance metrics */
  performance: {
    slowestOperationMs: number;
    fastestOperationMs: number;
    averageOperationMs: number;
  };

  /** Timestamp when statistics were collected */
  timestamp: Date;
}

export interface ISagaMonitor {
  /**
   * Record saga started event
   * @param sagaId - Saga identifier
   * @param sagaType - Type of saga
   * @param context - Execution context
   */
  recordSagaStarted(sagaId: string, sagaType: string, context: ISagaExecutionContext): void;

  /**
   * Record saga step executed
   * @param sagaId - Saga identifier
   * @param stepName - Name of executed step
   * @param duration - Execution duration in milliseconds
   * @param success - Whether step executed successfully
   */
  recordStepExecuted(sagaId: string, stepName: string, duration: number, success: boolean): void;

  /**
   * Record saga completed
   * @param sagaId - Saga identifier
   * @param totalDuration - Total saga duration in milliseconds
   * @param success - Whether saga completed successfully
   */
  recordSagaCompleted(sagaId: string, totalDuration: number, success: boolean): void;

  /**
   * Record saga error
   * @param sagaId - Saga identifier
   * @param error - Error information
   * @param step - Step where error occurred
   */
  recordSagaError(sagaId: string, error: Error, step: string): void;

  /**
   * Get monitoring metrics
   * @param filter - Optional filter criteria
   * @returns Monitoring metrics
   */
  getMetrics(filter?: ISagaMetricsFilter): ISagaMetrics;

  /**
   * Export metrics in specified format
   * @param format - Export format (json, csv, prometheus)
   * @param filter - Optional filter criteria
   * @returns Exported metrics data
   */
  exportMetrics(format: 'json' | 'csv' | 'prometheus', filter?: ISagaMetricsFilter): string;
}

export interface ISagaMetricsFilter {
  /** Saga type filter */
  sagaType?: string;

  /** Date range filter */
  dateRange?: {
    start: Date;
    end: Date;
  };

  /** Status filter */
  status?: string[];

  /** Include only sagas with errors */
  errorsOnly?: boolean;

  /** Include only slow sagas */
  slowSagasOnly?: boolean;

  /** Minimum duration filter (milliseconds) */
  minDuration?: number;
}

export interface ISagaMetrics {
  /** Summary statistics */
  summary: {
    totalSagas: number;
    completedSagas: number;
    failedSagas: number;
    compensatedSagas: number;
    activeSagas: number;
  };

  /** Performance metrics */
  performance: {
    averageDuration: number;
    medianDuration: number;
    p95Duration: number;
    p99Duration: number;
    throughput: number;
  };

  /** Error metrics */
  errors: {
    totalErrors: number;
    errorRate: number;
    errorsByType: Record<string, number>;
    errorsByStep: Record<string, number>;
  };

  /** Time series data */
  timeSeries: Array<{
    timestamp: Date;
    completed: number;
    failed: number;
    active: number;
    averageDuration: number;
  }>;

  /** Metric collection metadata */
  metadata: {
    collectionPeriod: {
      start: Date;
      end: Date;
    };
    filter: ISagaMetricsFilter;
    generatedAt: Date;
  };
}
